-- Fix123 / Faz 1
-- Canonical öğrenci + katalog şeması.
-- Bu migration production'a otomatik uygulanmamalıdır; önce preview/branch üzerinde doğrulanmalıdır.

begin;

create table if not exists public.pire_students (
  id bigint generated by default as identity primary key,
  full_name text not null,
  birth_date date,
  blood_group text,
  phone text,
  address text,
  national_id text,
  heard_from text,
  registration_date date not null default current_date,
  guardian_name text,
  guardian_relation text,
  guardian_phone text,
  guardian_phone_2 text,
  guardian_national_id text,
  emergency_contact text,
  monthly_fee numeric(12,2) not null default 0 check (monthly_fee >= 0),
  payment_day smallint not null default 1 check (payment_day between 1 and 31),
  status text not null default 'Aktif' check (status in ('Aktif','Kayıt dondurmuş','Ayrılmış')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.pire_students is 'Pİ-RE canonical öğrenci kayıtları. pire_ai_students yalnızca minimize AI snapshotıdır.';
comment on column public.pire_students.national_id is 'Hassas veri. İstemciye yalnızca yetkili akışlarda döndürülmelidir.';
comment on column public.pire_students.guardian_national_id is 'Hassas veri. İstemciye yalnızca yetkili akışlarda döndürülmelidir.';

create table if not exists public.pire_teachers (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text,
  backup_phone text,
  national_id text,
  birth_date date,
  start_date date,
  address text,
  emergency_contact text,
  availability text,
  iban text,
  compensation_type text,
  compensation_amount numeric(12,2) not null default 0 check (compensation_amount >= 0),
  group_compensation_amount numeric(12,2) not null default 0 check (group_compensation_amount >= 0),
  cancellation_rule text,
  status text not null default 'Aktif' check (status in ('Aktif','Ayrılmış','Pasif')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.pire_teachers is 'Pİ-RE canonical eğitmen kayıtları.';
comment on column public.pire_teachers.iban is 'Hassas finansal veri; admin-only erişim.';
comment on column public.pire_teachers.national_id is 'Hassas kimlik verisi; admin-only erişim.';

create table if not exists public.pire_courses (
  id bigint generated by default as identity primary key,
  name text not null,
  status text not null default 'Aktif' check (status in ('Aktif','Pasif')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists pire_courses_name_ci_uidx
  on public.pire_courses (lower(btrim(name)));

create table if not exists public.pire_teacher_courses (
  teacher_id bigint not null references public.pire_teachers(id) on delete cascade,
  course_id bigint not null references public.pire_courses(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (teacher_id, course_id)
);

create index if not exists pire_students_status_idx on public.pire_students(status);
create index if not exists pire_students_registration_date_idx on public.pire_students(registration_date desc);
create index if not exists pire_teachers_status_idx on public.pire_teachers(status);
create index if not exists pire_teacher_courses_course_idx on public.pire_teacher_courses(course_id);

-- Updated-at trigger helper. Aynı isimli helper varsa değiştirmeden kullanılır.
create or replace function private.pire_touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists pire_students_touch_updated_at on public.pire_students;
create trigger pire_students_touch_updated_at
before update on public.pire_students
for each row execute function private.pire_touch_updated_at();

drop trigger if exists pire_teachers_touch_updated_at on public.pire_teachers;
create trigger pire_teachers_touch_updated_at
before update on public.pire_teachers
for each row execute function private.pire_touch_updated_at();

drop trigger if exists pire_courses_touch_updated_at on public.pire_courses;
create trigger pire_courses_touch_updated_at
before update on public.pire_courses
for each row execute function private.pire_touch_updated_at();

-- RLS
alter table public.pire_students enable row level security;
alter table public.pire_teachers enable row level security;
alter table public.pire_courses enable row level security;
alter table public.pire_teacher_courses enable row level security;

-- Öğrenciler: admin yazabilir; Öğrenci/Veli/Eğitmen yalnızca mevcut ilişki fonksiyonunun izin verdiği öğrenciyi okuyabilir.
drop policy if exists pire_students_select_authorized on public.pire_students;
create policy pire_students_select_authorized
on public.pire_students
for select
to authenticated
using ((select private.current_user_can_access_pire_student(id)));

drop policy if exists pire_students_admin_insert on public.pire_students;
create policy pire_students_admin_insert
on public.pire_students
for insert
to authenticated
with check ((select private.current_user_is_pire_admin()));

drop policy if exists pire_students_admin_update on public.pire_students;
create policy pire_students_admin_update
on public.pire_students
for update
to authenticated
using ((select private.current_user_is_pire_admin()))
with check ((select private.current_user_is_pire_admin()));

drop policy if exists pire_students_admin_delete on public.pire_students;
create policy pire_students_admin_delete
on public.pire_students
for delete
to authenticated
using ((select private.current_user_is_pire_admin()));

-- Eğitmen canonical tablosu hassas alanlar içerdiğinden ilk fazda yalnızca aktif yönetici erişebilir.
drop policy if exists pire_teachers_admin_select on public.pire_teachers;
create policy pire_teachers_admin_select
on public.pire_teachers
for select
to authenticated
using ((select private.current_user_is_pire_admin()));

drop policy if exists pire_teachers_admin_insert on public.pire_teachers;
create policy pire_teachers_admin_insert
on public.pire_teachers
for insert
to authenticated
with check ((select private.current_user_is_pire_admin()));

drop policy if exists pire_teachers_admin_update on public.pire_teachers;
create policy pire_teachers_admin_update
on public.pire_teachers
for update
to authenticated
using ((select private.current_user_is_pire_admin()))
with check ((select private.current_user_is_pire_admin()));

drop policy if exists pire_teachers_admin_delete on public.pire_teachers;
create policy pire_teachers_admin_delete
on public.pire_teachers
for delete
to authenticated
using ((select private.current_user_is_pire_admin()));

-- Ders/branş isimleri hassas değildir: giriş yapan kullanıcı okuyabilir, yalnızca admin değiştirebilir.
drop policy if exists pire_courses_authenticated_select on public.pire_courses;
create policy pire_courses_authenticated_select
on public.pire_courses
for select
to authenticated
using (true);

drop policy if exists pire_courses_admin_insert on public.pire_courses;
create policy pire_courses_admin_insert
on public.pire_courses
for insert
to authenticated
with check ((select private.current_user_is_pire_admin()));

drop policy if exists pire_courses_admin_update on public.pire_courses;
create policy pire_courses_admin_update
on public.pire_courses
for update
to authenticated
using ((select private.current_user_is_pire_admin()))
with check ((select private.current_user_is_pire_admin()));

drop policy if exists pire_courses_admin_delete on public.pire_courses;
create policy pire_courses_admin_delete
on public.pire_courses
for delete
to authenticated
using ((select private.current_user_is_pire_admin()));

-- Eğitmen-branş bağlantısı isim/ilişki verisidir; giriş yapan kullanıcı okuyabilir, admin yazabilir.
drop policy if exists pire_teacher_courses_authenticated_select on public.pire_teacher_courses;
create policy pire_teacher_courses_authenticated_select
on public.pire_teacher_courses
for select
to authenticated
using (true);

drop policy if exists pire_teacher_courses_admin_insert on public.pire_teacher_courses;
create policy pire_teacher_courses_admin_insert
on public.pire_teacher_courses
for insert
to authenticated
with check ((select private.current_user_is_pire_admin()));

drop policy if exists pire_teacher_courses_admin_update on public.pire_teacher_courses;
create policy pire_teacher_courses_admin_update
on public.pire_teacher_courses
for update
to authenticated
using ((select private.current_user_is_pire_admin()))
with check ((select private.current_user_is_pire_admin()));

drop policy if exists pire_teacher_courses_admin_delete on public.pire_teacher_courses;
create policy pire_teacher_courses_admin_delete
on public.pire_teacher_courses
for delete
to authenticated
using ((select private.current_user_is_pire_admin()));

-- Bu fazda mevcut profile/AI foreign keyleri değiştirilmez.
-- Önce canonical veriler doğrulanacak, ardından ilişki FK geçişi ayrı migration ile yapılacaktır.

commit;
