create table if not exists public.pire_customers (
  id bigint generated by default as identity primary key,
  customer_code text,
  full_name text not null,
  phone text,
  service_type text not null default 'Stüdyo',
  project text,
  planned_date date,
  budget numeric(14,2),
  status text not null default 'Yeni Talep',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists pire_customers_customer_code_uq
  on public.pire_customers(customer_code) where customer_code is not null;
create index if not exists pire_customers_service_type_idx on public.pire_customers(service_type);
create index if not exists pire_customers_status_idx on public.pire_customers(status);

alter table public.pire_customers enable row level security;

drop policy if exists "pire_customers_admin_select" on public.pire_customers;
drop policy if exists "pire_customers_admin_insert" on public.pire_customers;
drop policy if exists "pire_customers_admin_update" on public.pire_customers;
drop policy if exists "pire_customers_admin_delete" on public.pire_customers;
create policy "pire_customers_admin_select" on public.pire_customers
  for select to authenticated using (private.current_user_is_pire_admin());
create policy "pire_customers_admin_insert" on public.pire_customers
  for insert to authenticated with check (private.current_user_is_pire_admin());
create policy "pire_customers_admin_update" on public.pire_customers
  for update to authenticated using (private.current_user_is_pire_admin()) with check (private.current_user_is_pire_admin());
create policy "pire_customers_admin_delete" on public.pire_customers
  for delete to authenticated using (private.current_user_is_pire_admin());
