"use strict";

const {send,rest,authenticate,dateOnly}=require("./_canonical");
function short(v,m=1000){return String(v??"").replace(/[\u0000-\u001f\u007f]/g,"").trim().slice(0,m)}
function id(v){const n=Number(v);return Number.isSafeInteger(n)&&n>0?n:null}
function date(v){const x=short(v,10);return /^\d{4}-\d{2}-\d{2}$/.test(x)?x:null}
async function write(token,path,method,body){return rest(token,path,{method,body:body===undefined?undefined:JSON.stringify(body),headers:body===undefined?{}:{Prefer:'return=representation,resolution=merge-duplicates'}})}
function makeupPayload(body){const studentId=id(body?.studentId),status=short(body?.status,80)||'Aktif';if(!studentId)return null;return {student_id:studentId,source_lesson_id:id(body?.sourceLessonId),makeup_lesson_id:id(body?.makeupLessonId),reason:short(body?.reason,1000)||null,expires_at:date(body?.expiresAt),status}}
function changePayload(body){const lessonId=id(body?.lessonId);if(!lessonId)return null;return {lesson_id:lessonId,action:short(body?.action,120)||null,old_date:date(body?.oldDate),new_date:date(body?.newDate),old_time:short(body?.oldTime,20)||null,new_time:short(body?.newTime,20)||null,old_status:short(body?.oldStatus,80)||null,new_status:short(body?.newStatus,80)||null,reason:short(body?.reason,1000)||null,changed_by:short(body?.changedBy,160)||null,changed_at:body?.changedAt||new Date().toISOString()}}
async function getAll(token){const [rights,changes]=await Promise.all([rest(token,'pire_makeup_rights?select=*&order=created_at.desc,id.desc'),rest(token,'pire_lesson_changes?select=*&order=changed_at.desc,id.desc')]);return {makeups:(rights||[]).map(r=>({id:Number(r.id),studentId:Number(r.student_id),sourceLessonId:r.source_lesson_id==null?null:Number(r.source_lesson_id),makeupLessonId:r.makeup_lesson_id==null?null:Number(r.makeup_lesson_id),reason:r.reason,expiresAt:dateOnly(r.expires_at),status:r.status,createdAt:r.created_at})),changes:(changes||[]).map(r=>({id:Number(r.id),lessonId:r.lesson_id==null?null:Number(r.lesson_id),action:r.action,oldDate:dateOnly(r.old_date),newDate:dateOnly(r.new_date),oldTime:r.old_time,newTime:r.new_time,oldStatus:r.old_status,newStatus:r.new_status,reason:r.reason,changedBy:r.changed_by,changedAt:r.changed_at}))}}

module.exports=async function handler(req,res){
  const method=String(req.method||'GET').toUpperCase();if(!['GET','POST','PATCH','PUT','DELETE'].includes(method))return send(res,405,{error:'Desteklenmeyen istek yöntemi.'},{Allow:'GET, POST, PATCH, PUT, DELETE'});
  try{
    const {token,identity}=await authenticate(req);if(method==='GET')return send(res,200,await getAll(token));if(!identity.roles.includes('Yönetici'))return send(res,403,{error:'Telafi değişiklikleri yalnızca Yönetici tarafından yapılabilir.'});
    const body=req.body||{},mode=short(body.type||body.kind||body.mode,30).toLocaleLowerCase('tr-TR');
    if(mode==='change'||mode==='lesson-change'||body.action!==undefined){const payload=changePayload(body);if(!payload)return send(res,400,{error:'Geçerli ders kimliği gerekiyor.'});const changeId=id(body.changeId??body.id);if(method==='DELETE'){if(!changeId)return send(res,400,{error:'Geçerli değişiklik kimliği gerekiyor.'});await rest(token,`pire_lesson_changes?id=eq.${changeId}`,{method:'DELETE'});return send(res,200,{ok:true,changeId,deleted:true})}if(method==='POST'){const created=await write(token,'pire_lesson_changes','POST',[payload]),row=Array.isArray(created)?created[0]:created;return send(res,201,{ok:true,change:{...body,id:Number(row.id)}})}if(!changeId)return send(res,400,{error:'Geçerli değişiklik kimliği gerekiyor.'});const updated=await write(token,`pire_lesson_changes?id=eq.${changeId}`,'PATCH',payload),row=Array.isArray(updated)?updated[0]:updated;return send(res,200,{ok:true,change:{...body,id:changeId,changedAt:row?.changed_at||payload.changed_at}})}
    const makeupId=id(body.makeupId??body.id);if(method==='DELETE'){if(!makeupId)return send(res,400,{error:'Geçerli telafi kimliği gerekiyor.'});const updated=await write(token,`pire_makeup_rights?id=eq.${makeupId}`,'PATCH',{status:'İptal'});return send(res,200,{ok:true,makeup:Array.isArray(updated)?updated[0]||null:updated,mode:'cancelled'})}
    const payload=makeupPayload(body);if(!payload)return send(res,400,{error:'Geçerli öğrenci kimliği gerekiyor.'});if(method==='POST'){const created=await write(token,'pire_makeup_rights','POST',[payload]),row=Array.isArray(created)?created[0]:created;if(!row?.id)return send(res,502,{error:'Telafi hakkı oluşturuldu fakat kimliği alınamadı.'});return send(res,201,{ok:true,makeup:{...body,id:Number(row.id),status:row.status,createdAt:row.created_at}})}if(!makeupId)return send(res,400,{error:'Geçerli telafi kimliği gerekiyor.'});const updated=await write(token,`pire_makeup_rights?id=eq.${makeupId}`,'PATCH',payload),row=Array.isArray(updated)?updated[0]:updated;return send(res,200,{ok:true,makeup:{...body,id:makeupId,status:row?.status||payload.status}})
  }catch(error){if(error?.detail)console.error('Canonical makeups failed',String(error.detail).slice(0,500));return send(res,error?.status||500,{error:error?.message||'Telafi işlemi tamamlanamadı.'})}
};

module.exports._test={makeupPayload,changePayload};
